CREATE TABLE public.venues (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  keyword text,
  province text,
  city text,
  full_address text,
  street text,
  postal_code text,
  state text,
  country text,
  phone text,
  reviews text,
  latitude numeric,
  longitude numeric,
  photo text,
  site text,
  street_view text,
  working_hours text,
  business_status text,
  location_link text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
